# Generated by Django 3.0.2 on 2020-01-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdata',
            name='studyTime',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
