# Generated by Django 3.0.2 on 2020-01-17 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphData', '0002_graphdata_studytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='category',
            field=models.ForeignKey(help_text='※任意', on_delete=django.db.models.deletion.PROTECT, to='graphData.Category'),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='studyTime',
            field=models.IntegerField(help_text='※任意'),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='title',
            field=models.CharField(help_text='※任意', max_length=50, verbose_name='タイトル'),
        ),
    ]
