# Generated by Django 3.0.2 on 2020-01-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphData', '0005_graphdata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdata',
            name='details',
            field=models.CharField(default=1, help_text='勉強の詳細', max_length=400, verbose_name='詳細'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='category',
            field=models.ForeignKey(help_text='学習した勉強のカテゴリ', on_delete=django.db.models.deletion.PROTECT, to='graphData.Category'),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='studyTime',
            field=models.IntegerField(help_text='学習時間', verbose_name='学習時間'),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='title',
            field=models.CharField(help_text='勉強タイトル', max_length=50, verbose_name='タイトル'),
        ),
    ]
