# Generated by Django 3.0.2 on 2020-01-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphData', '0006_auto_20200117_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='studyTime',
            field=models.FloatField(help_text='学習時間', verbose_name='学習時間'),
        ),
    ]
