# Generated by Django 3.0.2 on 2020-01-17 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphData', '0007_auto_20200117_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
