# Generated by Django 3.0.2 on 2020-01-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphData', '0008_auto_20200117_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphdata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='graphdata',
            name='studyDay',
            field=models.DateField(help_text='勉強日', verbose_name='勉強日'),
            preserve_default=False,
        ),
    ]
